config: '{"name":"test","age":100,"amount":9.9,"sex":true,"email":"email@email.com","phone":"123456789","ref1":"","ref2":"","ref3":""}'

ref1 : '{"ref1":"1","ref2":"2","ref3":"3","phone":"382493423423"}'
